; https://github.com/handledexception/platform-espressif32/blob/esp32-s3-devkitc-1-n16r8v/boards/esp32-s3-devkitc-1-n16r8v.json

[platformio]
default_envs = esp32-s3-n16r8-dev

[env:esp32-s3-n16r8-dev]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.partitions = partitions.csv
lib_deps = 
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-espeak-ng.git
    https://github.com/pschatzmann/arduino-posix-fs.git
build_flags = 
    -DCORE_DEBUG_LEVEL=5 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format-extra-args 
    -Wl,--allow-multiple-definition
monitor_speed = 115200
monitor_filters = esp32_exception_decoder